version: '3.8'
services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SYSTEM_PROMPT=${SYSTEM_PROMPT}
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - .:/app
    restart: unless-stopped
